config/routes.rb
Rails.application.routes.draw do

  
  
  Hadvis::Application.routes.draw do
 
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  get 'welcome/index'
  get 'admin/index'

  resources :hotels do
    resources :comments
    resources :votes
  end

  namespace :admin do
    resources :users
    resources :hotels
  end
  
  root :to =>'welcome#index'
  end

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :title, :country, :state, :country,  :city, :street, length:{ maximum: 255,too_long: "%{count} characters is the maximum allowed" }
  validates :title, :star_rating, presence:{ message: "field should not be empty" } 
  validates :price, :star_rating, numericality: true 
  validates :star_rating, inclusion: { in: 1..5, message: "%{value} is not a valid vote" } 
  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed" }

  #===========================
  #1 - да, 0 - нет
  #status:
  # 1-pending
  # 2-approved
  # 3-rejected
  #===========================

  def status_decode
    if self.status == 1 then return'pending'
    elsif self.status == 2 then return'approved'
    elsif self.status == 3 then return 'rejected'
    else return 'indefinitely'
    end
  end

  def self.search(search)
    if search
      where("status = #{search}")
    else
      all
    end
  end

  def top(size)
    temp = Hotel.select("hotels.*, COUNT(votes.id) AS rating").where("status = 2").joins("LEFT JOIN votes ON votes.hotel_id = hotels.id").group("hotels.id").order("rating desc").limit(size)
    return temp
  end


end

app/controllers/admin/hotels_controller.rb
module Admin
class HotelsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_admin_logged_in!
  helper_method :sort_column, :sort_direction

# метод показать все записи
  def index
    @hotels = Hotel.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
  end

# метод редактировать
  def edit
    @hotel = Hotel.find(params[:id])
    if @hotel.status != 1 then
      render text: "You can't change this status"
    end
  end
  # метод обновить применяется только для обновления статуса и отправки уведомления
  def update
    @hotel = Hotel.find(params[:id])
      if @hotel.update(hotel_params)

        UserMailer.status_changed(User.find(@hotel.user_id),@hotel).deliver
        redirect_to admin_hotels_path
      else
        render 'edit'
      end
  end

# метод удалить  
  def destroy
    unless @hotel= Hotel.where(id: params[:id]).first
      render text: "Page not found", status: 404
    else
      @hotel.destroy
      redirect_to admin_hotels_path
    end
  end

  private
    def check_admin_logged_in! # admin must be logged in
      if user_signed_in? then
        unless User.is_admin?(current_user.role) then redirect_to root_path end
      end
    end
  
    def sort_column
      Hotel.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def hotel_params
      params.require(:hotel).permit(:status)
    end
  end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :check_admin_logged_in!, :except => [:show, :index,:new, :create]
  helper_method :sort_column, :sort_direction

 # метод 
  def new
    @hotel = Hotel.new 
  end



#метод создать запись
  def create
    @hotel = Hotel.new(hotel_params)
    @hotel.user_id = current_user.id
    @hotel.status = 1 #pending
    if @hotel.save
      redirect_to @hotel
    else
      render 'new'
    end
  end

# метод показать запись по id
  def show
    unless @hotel= Hotel.where(id: params[:id]).first
      render text: "Page not found", status: 404
    end
  end

# метод показать все записи где статус approved т.е. 2
  def index
    @hotels = Hotel.where(status: 2).order(sort_column + " " + sort_direction)
  end

# метод редактировать
  def edit
    @hotel = Hotel.find(params[:id])
  end
  # метод обновить
  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update(hotel_params)
      redirect_to @hotel
    else
      render 'edit'
    end
  end

# метод удалить  
  def destroy
    unless @hotel= Hotel.where(id: params[:id]).first
      render text: "Page not found", status: 404
    else
      @hotel.destroy
      redirect_to hotels_path
    end
end

  private
    def check_admin_logged_in! # admin must be logged in
      if user_signed_in? then
        unless User.is_admin?(current_user.role) then redirect_to root_path end
      end
    end
  
    def sort_column
      Hotel.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def hotel_params
      params.require(:hotel).permit(:title, :description, :star_rating, 
      :breakfast_in, :price, :country, :state, :street,:image, :city)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/admin/hotels/_status_search_form.html.haml
= form_tag admin_hotels_path, :method => 'get' do
  = hidden_field_tag :direction, params[:direction] 
  = hidden_field_tag :sort, params[:sort]
  %p
    = select_tag(:search, options_for_select([['pending', 1], ['approved', 2],['rejected',3] ], params[:search]))
    = submit_tag "Search", :status => nil

app/views/admin/hotels/edit.html.haml
%h3 Editing the post

%div.col-md-4
  %div.panel.panel-success
    %div.panel-heading

    %div.panel-body
      = simple_form_for @hotel, :url => admin_hotel_path, :html=> { :class=>'form-horizontal'}, wrapper: :horizontal_form  do |f| 
        = f.input :status, collection: [['pending',1],['approved',2],['rejected',3]]
        %div.pull-right
          = f.button :submit, :class =>'btn btn-success'
= link_to 'Back', admin_hotels_path
 

app/views/admin/hotels/index.html.haml
%div.col-md-11
  %h3 Hotels
  %div.panel.panel-success
    %div.panel-heading
    %div.panel-body                
      %table.table.table-striped.table-bordered.table-condensed
        %thead
          %tr
            %th.text-center
              %span.glyphicon.glyphicon-sort
              = sortable "id","btn btn-link"
            %th.text-center
              Image  
            %th.text-center
              %span.glyphicon.glyphicon-sort
              = sortable "title", "btn btn-link"
            %th.text-center
              %span.glyphicon.glyphicon-sort
              = sortable "country","btn btn-link"
            %th.text-center
              %span.glyphicon.glyphicon-sort
              = sortable "price","btn btn-link"
            %th.text-center
              %span.glyphicon.glyphicon-sort
              = sortable "status","btn btn-link"
            %th{colspan:2, class:"text-center"}Options
        %tbody
          %tr
            %td{colspan:5}
            %td.text-center
              = render 'status_search_form'
            %td.text-center{colspan:2}
              = link_to 'Reset filters', admin_hotels_path, {:class => 'btn btn-default'}
         
          -@hotels.each do |hotel|
            %tr
              %td= hotel.id
              %td  
                =image_tag(hotel.image.url(:thumb_min))
              %td= hotel.title
              %td= hotel.country
              %td= hotel.price
              %td
                = hotel.status_decode
                -if hotel.status == 1 #pending
                  = link_to 'Change', edit_admin_hotel_path(hotel)  
              %td
                %span.glyphicon.glyphicon-pencil
                = link_to 'Edit', edit_hotel_path(hotel)
              %td
                %span.glyphicon.glyphicon-trash
                = link_to 'Delete', admin_hotel_path(hotel),method: :delete, data: { confirm: '  Are you sure?' }
      = will_paginate @hotels