config/routes.rb
Rails.application.routes.draw do

  
  
  Hadvis::Application.routes.draw do
 
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  get 'welcome/index'
  get 'admin/index'

  resources :hotels do
    resources :comments
    resources :votes
  end

  namespace :admin do
    resources :users
    resources :hotels
  end
  
  root :to =>'welcome#index'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :hotels
  has_many :votes #окончание имеет значение!	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  Admin = "admin"
  Common = "user"
  Is_admin = 1

  def self.is_admin?(role)
    if role == Is_admin then return true
    else 
      return false
    end
  end

  def getrole
    self.role == 1? @getrole = Admin : @getrole = Common
  end

  def self.search(search,field)
  if search
    where("#{field} LIKE ?", "%#{search}%")
  else
    all
  end
end
  
end

app/controllers/admin/users_controller.rb
module Admin
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_admin_logged_in!

  helper_method :sort_column, :sort_direction

  def new
    @user = User.new
  end

# метод показать все записи
  def index
    @users = get_sorted
  end

  # метод показать запись по id
  def show
    unless @user= User.where(id: params[:id]).first
      render text: "Page not found", status: 404
    end
  end

# метод редактировать
  def edit
    @user = User.find(params[:id])
  end
  # метод обновить
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render 'edit'
    end
  end

# метод удалить  
  def destroy
    unless @user= User.where(id: params[:id]).first
      render text: "Page not found", status: 404
    else
      @user.destroy
      redirect_to admin_users_path
    end
end

  private
    def check_admin_logged_in! # admin must be logged in
      if user_signed_in? then
        unless User.is_admin?(current_user.role) then redirect_to root_path end
      end
    end
  
    def sort_column
      User.column_names.include?(params[:sort]) || %w[hotels votes comments].include?(params[:sort]) ? params[:sort] : "id"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def get_sorted
      query = nil
      if User.column_names.include?(params[:sort]) then

        query = User.search(params[:search],params[:field]).order(params[:sort] + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])

      elsif %w[hotels votes comments].include?(params[:sort]) then

        query = User.search(params[:search],params[:field]).select("users.*, COUNT("+params[:sort]+".id) AS "+params[:sort]).joins("LEFT JOIN "+ params[:sort]+ " ON "+params[:sort]+".user_id = users.id").group("users.id").order(params[:sort] + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])

      else query = User.search(params[:search],params[:field]).order("id " + sort_direction).paginate(:per_page => 5, :page => params[:page])

      end
      return query  
    end

    def user_params
      params.require(:user).permit(:email, :role, :name, :password, :password_confirmation)
    end
end

end

app/views/admin/users/_email_search_form.html.haml
= form_tag admin_users_path, :method => 'get' do
  = hidden_field_tag :direction, params[:direction] 
  = hidden_field_tag :sort, params[:sort]
  = hidden_field_tag :field, :email
  = text_field_tag :search, nil, :class => 'form-control input-sm'
  = submit_tag "Search", :email => nil

app/views/admin/users/_form.html.haml
%div.col-md-4
  %div.panel.panel-success
    %div.panel-heading

    %div.panel-body
      = simple_form_for @user, :url => admin_user_path, :html=> { :class=>'form-horizontal'}, wrapper: :horizontal_form  do |f| 
        = f.input :email
        = f.input :name
        = f.input :role, collection: [['admin',1],['user',0]], label:'role'

        %div.pull-right
          = f.button :submit, :class =>'btn btn-success'

app/views/admin/users/_name_search_form.html.haml
= form_tag admin_users_path, :method => 'get' do
  = hidden_field_tag :direction, params[:direction] 
  = hidden_field_tag :sort, params[:sort]
  = hidden_field_tag :field, :name
  %p
    = text_field_tag :search, nil,:class => 'form-control input-sm'
    = submit_tag "Search", :name => nil

app/views/admin/users/edit.html.haml
%h3 Editing the post

= render 'form'
= link_to 'Back', admin_users_path
 

app/views/admin/users/index.html.haml
%div.col-md-11
  %h3 Users
  %div.panel.panel-success
    %div.panel-heading
    %div.panel-body                
      %table.table.table-striped.table-bordered.table-condensed
        %tr
          %th.text-center
            %span.glyphicon.glyphicon-sort
            = sortable "id","btn btn-link"
          %th.text-center
            %span.glyphicon.glyphicon-sort
            = sortable "name", "btn btn-link"
          %th.text-center
            %span.glyphicon.glyphicon-sort
            = sortable "email", "btn btn-link"
          %th.text-center
            %span.glyphicon.glyphicon-sort
            = sortable "role","btn btn-link"
          %th.text-center
            %span.glyphicon.glyphicon-sort
            = sortable "votes","btn btn-link"
          %th.text-center
            %span.glyphicon.glyphicon-sort
            = sortable "comments","btn btn-link"
          %th.text-center
            %span.glyphicon.glyphicon-sort
            = sortable "hotels","btn btn-link"
          %th{colspan:3, class:"text-center"}Options
        %tr
          %td
          %td.text-right
            = render 'name_search_form'
          %td.text-right
            = render 'email_search_form'
          %td{colspan:4}
          %td{colspan:2}
            = link_to 'Reset filters', admin_users_path, {:class => 'btn btn-default'}
            %br
            = link_to 'Create user', new_user_registration_path, {:class => 'btn btn-default'}
        -@users.each do |user|
          %tr
            %td= user.id
            %td= user.name
            %td= user.email
            %td= user.getrole
            %td= user.votes.count
            %td= user.comments.count
            %td= user.hotels.count
            %td
              %span.glyphicon.glyphicon-pencil
              = link_to 'Edit', edit_admin_user_path(user)
            %td
              %span.glyphicon.glyphicon-trash
              = link_to 'Delete', admin_user_path(user),method: :delete, data: { confirm: '  Are you sure?' }
              
      = will_paginate @users