config/routes.rb
Rails.application.routes.draw do

  
  
  Hadvis::Application.routes.draw do
 
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  get 'welcome/index'
  get 'admin/index'

  resources :hotels do
    resources :comments
    resources :votes
  end

  namespace :admin do
    resources :users
    resources :hotels
  end
  
  root :to =>'welcome#index'
  end

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :title, :country, :state, :country,  :city, :street, length:{ maximum: 255,too_long: "%{count} characters is the maximum allowed" }
  validates :title, :star_rating, presence:{ message: "field should not be empty" } 
  validates :price, :star_rating, numericality: true 
  validates :star_rating, inclusion: { in: 1..5, message: "%{value} is not a valid vote" } 
  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed" }

  #===========================
  #1 - да, 0 - нет
  #status:
  # 1-pending
  # 2-approved
  # 3-rejected
  #===========================

  def status_decode
    if self.status == 1 then return'pending'
    elsif self.status == 2 then return'approved'
    elsif self.status == 3 then return 'rejected'
    else return 'indefinitely'
    end
  end

  def self.search(search)
    if search
      where("status = #{search}")
    else
      all
    end
  end

  def top(size)
    temp = Hotel.select("hotels.*, COUNT(votes.id) AS rating").where("status = 2").joins("LEFT JOIN votes ON votes.hotel_id = hotels.id").group("hotels.id").order("rating desc").limit(size)
    return temp
  end


end

app/controllers/admin/hotels_controller.rb
module Admin
class HotelsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_admin_logged_in!
  helper_method :sort_column, :sort_direction

# метод показать все записи
  def index
    @hotels = Hotel.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])
  end

# метод редактировать
  def edit
    @hotel = Hotel.find(params[:id])
    if @hotel.status != 1 then
      render text: "You can't change this status"
    end
  end
  # метод обновить применяется только для обновления статуса и отправки уведомления
  def update
    @hotel = Hotel.find(params[:id])
      if @hotel.update(hotel_params)

        UserMailer.status_changed(User.find(@hotel.user_id),@hotel).deliver
        redirect_to admin_hotels_path
      else
        render 'edit'
      end
  end

# метод удалить  
  def destroy
    unless @hotel= Hotel.where(id: params[:id]).first
      render text: "Page not found", status: 404
    else
      @hotel.destroy
      redirect_to admin_hotels_path
    end
  end

  private
    def check_admin_logged_in! # admin must be logged in
      if user_signed_in? then
        unless User.is_admin?(current_user.role) then redirect_to root_path end
      end
    end
  
    def sort_column
      Hotel.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def hotel_params
      params.require(:hotel).permit(:status)
    end
  end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  before_filter :check_admin_logged_in!, :except => [:show, :index,:new, :create]
  helper_method :sort_column, :sort_direction

 # метод 
  def new
    @hotel = Hotel.new 
  end



#метод создать запись
  def create
    @hotel = Hotel.new(hotel_params)
    @hotel.user_id = current_user.id
    @hotel.status = 1 #pending
    if @hotel.save
      redirect_to @hotel
    else
      render 'new'
    end
  end

# метод показать запись по id
  def show
    unless @hotel= Hotel.where(id: params[:id]).first
      render text: "Page not found", status: 404
    end
  end

# метод показать все записи где статус approved т.е. 2
  def index
    @hotels = Hotel.where(status: 2).order(sort_column + " " + sort_direction)
  end

# метод редактировать
  def edit
    @hotel = Hotel.find(params[:id])
  end
  # метод обновить
  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update(hotel_params)
      redirect_to @hotel
    else
      render 'edit'
    end
  end

# метод удалить  
  def destroy
    unless @hotel= Hotel.where(id: params[:id]).first
      render text: "Page not found", status: 404
    else
      @hotel.destroy
      redirect_to hotels_path
    end
end

  private
    def check_admin_logged_in! # admin must be logged in
      if user_signed_in? then
        unless User.is_admin?(current_user.role) then redirect_to root_path end
      end
    end
  
    def sort_column
      Hotel.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def hotel_params
      params.require(:hotel).permit(:title, :description, :star_rating, 
      :breakfast_in, :price, :country, :state, :street,:image, :city)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.haml
%div.col-md-6
  %div.panel.panel-success
    %div.panel-heading

    %div.panel-body
      = simple_form_for @hotel, :html=> { :class=>'form-horizontal', :multipart=> true }, wrapper: :horizontal_form,wrapper_mappings: {check_boxes: :horizontal_radio_and_checkboxes,radio_buttons: :horizontal_radio_and_checkboxes,file: :horizontal_file_input,boolean: :horizontal_boolean}  do |f| 
        = f.input :title
        = f.input :star_rating, as: :radio_buttons, collection: [['1', '1'],['2', '2'],['3', '3'],['4', '4'],['5', '5']], label: 'Star rating'
        = f.input :description, input_html: { rows: 6}
        = f.input :breakfast_in, as: :boolean, cheked_value: 1, uncheked_value: 0, label: 'Breakfast included'
        = f.input :price, label: 'Price for room'
        = f.input :image, as: :file
        %div.row      
          %div.col-md-3.col-xs-6.col-md-offset-3
            %a{href: '#', class: 'thumbnail'}
              =image_tag(@hotel.image.url(:thumb_md)) if @hotel.image?
      
        = f.hidden_field :image_cache
        = f.input :country
        = f.input :state
        = f.input :city
        = f.input :street
        %div.pull-right
          = f.button :submit, :class =>'btn btn-success'

app/views/hotels/edit.html.haml
%h3 Editing the post
= link_to 'Back', hotels_path
= render 'form'
 

app/views/hotels/index.html.haml
%span.glyphicon.glyphicon-sort
= sortable "title", "btn btn-default"
= sortable "price","btn btn-default"
%div.col-md-9
  %h3 List of hotels
  -@hotels.each do |hotel|
    %div.panel.panel-success
      %div.panel-heading
        %h3.panel-title= hotel.title

      %div.panel-body
        %div.col-md-3  
          %a{href: '#', class: 'thumbnail'}
            =image_tag(hotel.image.url(:thumb_md))
        %div.col-md-8
        
          %p
            %strong Star rating:
            %button{ "type"=>"button", class:"btn btn-link"}
              - hotel.star_rating.times do
                %span.glyphicon.glyphicon-star

          %p    
            %strong Rating:
            = hotel.votes.sum('mark')
          %p    
            %strong Address:
            = hotel.country
            = hotel.state
            = hotel.city
            = hotel.street
          %p    
            %strong Price:
            = hotel.price

        %div.col-md-12.text-right

          %span{ class: "glyphicon glyphicon-search"}
          = link_to 'Show', hotel_path(hotel)
          -if user_signed_in? 

            -if User.is_admin?(current_user.role)

              %span{ class: "glyphicon glyphicon-pencil"}
              = link_to 'Edit', edit_hotel_path(hotel)
              %span{ class: "glyphicon glyphicon-trash"}
              = link_to 'Delete', hotel_path(hotel),method: :delete, data: { confirm: 'Are you sure?' }

app/views/hotels/new.html.haml
%h3 Add a new hotel
= link_to 'Back', hotels_path
= render 'form'

app/views/hotels/show.html.haml
%div.row.text-right
  %div.col-md-10
    = link_to  hotels_path do 
      %span.glyphicon.glyphicon-arrow-left
        Back
    -if user_signed_in? 
      -if User.is_admin?(current_user.role)  
        = link_to edit_hotel_path(@hotel)do 
          %span.glyphicon.glyphicon-edit
            Edit
%div.row.col-md-offset-1
  
  %div.col-md-4  
    %a{href: '#', class: 'thumbnail',"data-toggle"=>"modal", "data-target"=>".myModal"}
      =image_tag(@hotel.image.url(:thumb_md))
  %div.col-md-6
    %h4
      %strong Title:
      = @hotel.title
    
    %h4
      %strong Star rating:
      - @hotel.star_rating.times do
        %span.glyphicon.glyphicon-star
    
    %h4
      %strong Address:
      = @hotel.country
      = @hotel.state
      = @hotel.city
      = @hotel.street
    
    %h4
      %strong Breakfast including:
      = @hotel.breakfast_in == 1? "yes" : "no"
    
    %h4
      %strong Price:
      = @hotel.price

    %h4
      %strong Rating:
      = @hotel.votes.sum('mark')

    %p.text-justify
      %strong Description:
      = @hotel.description
%div.row.col-md-offset-1
  = render "votes/form"
  -if flash[:alert]
    %div.alert.alert-danger= flash[:alert]


%div.row.col-md-offset-1

  -if @hotel.comments.any?
    %h4 Comments 
    = render @hotel.comments

  %h4 Add a comment:
  = render "comments/form"

  = render "parts/image_modal"

  