config/routes.rb
Rails.application.routes.draw do

  
  
  Hadvis::Application.routes.draw do
 
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  get 'welcome/index'
  get 'admin/index'

  resources :hotels do
    resources :comments
    resources :votes
  end

  namespace :admin do
    resources :users
    resources :hotels
  end
  
  root :to =>'welcome#index'
  end

end

app/views/layouts/_navbar.html.haml
%nav{ class:"navbar navbar-default navbar-fixed-top", "role"=>"navigation" }
  %div.container
    %ul.nav.navbar-nav
      %li
        = link_to  welcome_index_path do 
          %span.glyphicon.glyphicon-home
            Home
      %li
        = link_to  hotels_path do 
          %span.glyphicon.glyphicon-list
            Hotels

      %li
        = link_to new_hotel_path do
          %span.glyphicon.glyphicon-plus 
            Add a hotel
          
      -if user_signed_in? 
        -if User.is_admin?(current_user.role)
          %li
            = link_to admin_index_path do
              %span.glyphicon.glyphicon-dashboard 
                Dashboard
     

app/views/layouts/_sign_links.html.haml
- if current_user
  = "Hello, #{current_user.email}"
  = link_to "Sign out", destroy_user_session_path, :method => :delete
- else
  = link_to "Sign in", new_user_session_path,:class => 'btn btn-small'
  = link_to "Sign up", new_user_registration_path,:class => 'btn btn-small'

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Hotels
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags

  %body
    = render "layouts/navbar"
  
    %div.container.bg-success
      = render "layouts/sign_links"

    
      %div.col-md-offset-2
        %h1.text-muted Hotel Advisor
    
    %div.container.bg-warning
      %div.row
        = yield